[build]
  publish = "."

[[redirects]]
  from = "/"
  to = "/landing.html"
  status = 200

[[redirects]]
  from = "/app"
  to = "/app.html"
  status = 200

[[redirects]]
  from = "/login"
  to = "/login.html"
  status = 200

[functions]
  directory = "netlify/functions"
