[build]
  publish = "."

[[redirects]]
  from = "/"
  to = "/landing.html"
  status = 200

[[redirects]]
  from = "/app"
  to = "/app.html"
  status = 200

[[redirects]]
  from = "/login"
  to = "/login.html"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[functions.openai-transcribe]
  node_version = "18"

[functions.openai-chat]
  node_version = "18"
  timeout = 26
